#docker run -d --hostname rabbitmq --name rabbitmq-management -p 15672:15672 -p 5671:5671 -p 5672:5672 rabbitmq:management
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest